version: "3"

services:

    web:
        container_name: pixels_web
        build: .
        volumes:
            - ./pixels:/var/www/vhosts/site/
        working_dir: /var/www/vhosts/site
        command: "/usr/sbin/php-fpm7.2 -F -O"
        user: "www-data"

    nginx:
        container_name: pixels_nginx
        image: nginx
        expose:
            - "80"
        ports:
            - "80:80"
        volumes:
            - ./pixels:/var/www/vhosts/site/
            - ./etc/nginx:/etc/nginx

    mysql:
        container_name: pixels_mysql
        image: mysql:5.7
        volumes:
            - ./etc/mysql:/etc/mysql/conf.d
            - ./storage/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
